### ISSUE TITLE
Homework Feedback

### ISSUE THREAD

**Issue by arun-instructor** [jenn-rhim/w4d1-hw-bootstrap#1]
Jenn,

Nice work on this. You implemented components well and placed in meaningful comments. We looked at components that would be a better fit, but I think you're on the right track. As an FYI, these types of resets are already done for you in Bootstrap:

```css
.body {
  margin:0;
  padding:0;
}
```

Cool huh? :)
